openapi: 3.0.3
info:
  title: txproc-design-first-openapi
  version: "0.9"
servers:
- url: http://localhost:8080
paths:
  /api/txproc/pincheck:
    post:
      summary: Check the pin
      operationId: pinCheck
      requestBody:
        description: PIN Check Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PinCheckRequest'
      responses:
        default:
          description: PIN Check Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PinCheckResponse'
  /api/txproc/purchase:
    post:
      summary: Authorize a Purchase
      operationId: purchase
      requestBody:
        description: Purchase Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseAuthRequest'
      responses:
        default:
          description: Purchase Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseAuthResponse'
components:
  schemas:
    EmvTags:
      description: Collection of EMV tags
      title: EmvTags
      type: object
      properties:
        84:
          description: The EMV AID as reported by ICC
          title: Dedicated Filename
          type: string
        9F1A:
          description: Terminal Country Code
          type: string
    Pan:
      description: The number embossed on credit cards
      title: PAN (Primary Account Number)
      # type: string would make Swagger-UI prettier, but can't use own type
      type: object
      format: string
    PinCheckRequest:
      description: Request for checking a PIN
      required:
      - pan
      - pinBlock
      - uuid
      properties:
        pan:
          $ref: '#/components/schemas/Pan'
        pinBlock:
          description: |-
            Encrypted binary data containing a PIN

            Fieldcode: C003
          type: string
        uuid:
          description: Unique ID of the request
          format: uuid
          type: string
      type: object
    PinCheckResponse:
      description: Tells if the PIN in the request was correct
      properties:
        result:
          description: Result of the request
          enum:
          - OK
          - WRONG
          type: string
        tries:
          description: Number of remaining tries
          format: int32
          type: integer
      type: object
    PurchaseAuthRequest:
      description: Request for authorizing a Purchase
      required:
      - pan
      - uuid
      properties:
        emvTags:
          $ref: '#/components/schemas/EmvTags'
        pan:
          $ref: '#/components/schemas/Pan'
        uuid:
          description: Unique ID of the request
          format: uuid
          type: string
      type: object
    PurchaseAuthResponse:
      description: Response to PurchaseAuthRequest
      properties:
        approvalCode:
          description: Code referencing the successful authorization
          type: string
        result:
          description: Result of the request
          enum:
          - OK
          - WRONG
          type: string
      type: object
